### ISSUE TITLE
Expose props of a file

### ISSUE THREAD

**Issue by provokateurin** [flymzero/webdav_client#11]
It would be nice to access the props of a file directly, because they contain information that sometimes is useful or necessary to access. For example Nextcloud makes use of this heavily.

**Comment by flymzero** [comment]
ok, i'll take a look

**Comment by jld3103** [comment]
I can also make a PR if you want :) Just wanted to note down, that the feature would be appreciated. I don't know when I will have the time exactly though.

**Comment by flymzero** [comment]
I'm glad you can make a PR😋. I checked [Nextcloud](https://github.com/jld3103/dart-nextcloud/blob/master/lib/src/webdav/file.dart). The props you said should be the attribute corresponding to XML. I'm busy with other things now. Later, I'm going to change it and optimize the structure and dependency

**Comment by jld3103** [comment]
I'm making a rewrite/starting from scratch with that library and I decided to not keep my own implementation of WebDAV. As I'll be a heavy consumer of this library, I'll probably contribute some stuff in the future.

**Comment by flymzero** [comment]
I'm very glad you can contribute code😁
