### ISSUE TITLE
Support Flutter Web?

### ISSUE THREAD

**Issue by Colin-XKL** [flymzero/webdav_client#12]
Awesome plugin, Any idea about supporting flutter for web?

**Comment by flymzero** [comment]
I need a little change, I'll try to submit the new version today

**Comment by flymzero** [comment]
I have released version 1.1.5, you can update it later and use it to support Web.
(see [stackoverflow](https://stackoverflow.com/questions/65630743/how-to-solve-flutter-web-api-cors-error-only-with-dart-code) for CORSB problems needing attention)
![web](https://raw.githubusercontent.com/flymzero/webdav_client/main/images/1.png)

**Comment by Colin-XKL** [comment]
bravo! 👍
