### ISSUE TITLE
Dont resolve the 301 Moved Permanently

### ISSUE THREAD

**Issue by nespjin** [flymzero/webdav_client#16]
I/flutter (25148): *** Response ***
I/flutter (25148): uri: https://aki.teracloud.jp/dav/backup/***/*****
I/flutter (25148): statusCode: 301
I/flutter (25148): headers:
I/flutter (25148):  content-type: text/html; charset=iso-8859-1
I/flutter (25148):  location: https://aki.teracloud.jp/dav/backup/***/*****
I/flutter (25148):  date: Sat, 21 May 2022 11:17:35 GMT
I/flutter (25148):  content-length: 276
I/flutter (25148):  server: Apache
I/flutter (25148): Response Text:
I/flutter (25148): <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
I/flutter (25148): <html><head>
I/flutter (25148): <title>301 Moved Permanently</title>
I/flutter (25148): </head><body>
I/flutter (25148): <h1>Moved Permanently</h1>
I/flutter (25148): <p>The document has moved <a href="https://aki.teracloud.jp/dav/backup/***/****/">here</a>.</p>
I/flutter (25148): </body></html>
I/flutter (25148): 
I/flutter (25148): 
I/flutter (25148): DioError [DioErrorType.response]: Moved Permanently

**Comment by flymzero** [comment]
A little more specific information is needed, such as request data

**Comment by flymzero** [comment]
There is no reply. I will close this question first and open it again if there is any supplement
