### ISSUE TITLE
Work with https

### ISSUE THREAD

**Issue by Alisofin** [flymzero/webdav_client#21]
Hello,
How does it work with https connection ? Could you please help ?

**Comment by flymzero** [comment]
this is support https, i test 坚果云（https） ok

**Comment by palorotolo** [comment]
> this is support https, i test 坚果云（https） ok

有连接坚果云的样例代码吗？

**Comment by parcool** [comment]
屏蔽了dio.httpClientAdapter的设置，无法使用自签证书等等。。。。
