### ISSUE TITLE
Can not build with dio 5.1.0

### ISSUE THREAD

**Issue by sunjianan9900** [flymzero/webdav_client#27]
```
Error (Xcode): /Users/sunjianan/.pub-cache/hosted/pub.flutter-io.cn/webdav_client-1.2.0/lib/src/webdav_dio.dart:354:60: Error: Too many positional arguments: 2 allowed, but 3 found.
```

**Comment by shAdow-XJY** [comment]
I met the same problem....QWQ
AppData/Local/Pub/Cache/hosted/pub.dev/webdav_client-1.2.0/lib/src/webdav_dio.dart(354,60): error G2E8E3A52: Too many positional arguments: 2 allowed, but 3 found.

**Comment by flymzero** [comment]
have uploaded to pub.dev 1.2.1
