### ISSUE TITLE
Feature Request: Recursive Get all Files

### ISSUE THREAD

**Issue by Y0ngg4n** [flymzero/webdav_client#4]
Maybe it is possible to include recursive read of files?

Example:
```
- dir1
  - dir2
  - file 2
    - dir3
    - file1
 ```

so when i request `dir1` i want to get `file2` and `file1`

Is that possible to include?

**Comment by flymzero** [comment]
I don't think this feature should be implemented, this should be implemented in the project itself, sorry.

**Comment by Y0ngg4n** [comment]
Ok allright
