### ISSUE TITLE
如何在线播放视频？

### ISSUE THREAD

**Issue by wengxianxun** [flymzero/webdav_client#45]
目前只能下载视频文件到本地，怎么直接在线播放呢？

**Comment by flymzero** [comment]
方案1：目前提供的读取文件方法（client.read），是获取整个文件内容(List<int>类型), 你可以尝试使用该数据对接到对应的音视频客户端，但是如果文件过大，就不建议这么弄
方案2（理论可行）：webdav也是基于http协议的，你先看看魔改一下拿到client.read对应的请求体，然后对接到对应支持http源的客户端

我应该可能后期会提供一个流式输出结果的方法，更大概率重写整个项目

**Comment by flymzero** [comment]
#34
