### ISSUE TITLE
Ping and readDir leads to exception

### ISSUE THREAD

**Issue by christianfl** [flymzero/webdav_client#7]
Using your package like that:

```
var client = webdav.newClient(
  _serverUrlController.text,
  user: _usernameController.text,
  password: _passwordController.text,
  debug: true,
);

client.setHeaders({'accept-charset': 'utf-8'});
client.setConnectTimeout(8000);
client.setSendTimeout(8000);
client.setReceiveTimeout(8000);
```

Then with both:

```
try {
  await client.ping();
} catch (e) {
  print('$e');
}
```

and

```
var list = await client.readDir('/');
list.forEach((f) {
  print('${f.name} ${f.path}');
});
```

I get the following error:

```
I/flutter ( 5604): Response Text:
I/flutter ( 5604): <?xml version="1.0" encoding="utf-8"?>
I/flutter ( 5604): <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
I/flutter ( 5604):   <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
I/flutter ( 5604):   <s:message>No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured</s:message>
I/flutter ( 5604): </d:error>
2
I/flutter ( 5604):
E/flutter ( 5604): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Exception: "www-authenticate" header has more than one value, please use Headers[name]
```

Printing the AuthType shows: noAuth. Should the authType be automatically selected?
Do you have any idea what's wrong?

**Comment by flymzero** [comment]
> Using your package like that:
> 
> ```
> var client = webdav.newClient(
>   _serverUrlController.text,
>   user: _usernameController.text,
>   password: _passwordController.text,
>   debug: true,
> );
> 
> client.setHeaders({'accept-charset': 'utf-8'});
> client.setConnectTimeout(8000);
> client.setSendTimeout(8000);
> client.setReceiveTimeout(8000);
> ```
> 
> Then with both:
> 
> ```
> try {
>   await client.ping();
> } catch (e) {
>   print('$e');
> }
> ```
> 
> and
> 
> ```
> var list = await client.readDir('/');
> list.forEach((f) {
>   print('${f.name} ${f.path}');
> });
> ```
> 
> I get the following error:
> 
> ```
> I/flutter ( 5604): Response Text:
> I/flutter ( 5604): <?xml version="1.0" encoding="utf-8"?>
> I/flutter ( 5604): <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
> I/flutter ( 5604):   <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
> I/flutter ( 5604):   <s:message>No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured</s:message>
> I/flutter ( 5604): </d:error>
> 2
> I/flutter ( 5604):
> E/flutter ( 5604): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Exception: "www-authenticate" header has more than one value, please use Headers[name]
> ```
> 
> Printing the AuthType shows: noAuth. Should the authType be automatically selected?
> Do you have any idea what's wrong?

Can you give me a test address? I'm looking at the documentation for "https://sabre.io/" and I don't know how to build this webdav service (haven't studied php 🤣)

**Comment by flymzero** [comment]
@christianfl Can you give me a test address? I'm looking at the documentation for "https://sabre.io/" and I don't know how to build this webdav service (haven't studied php 🤣)
